---
- name: ryu deployment
  hosts: ryu
  tasks:
    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      become: True
      with_items:
        - git
        - mininet
        - python-dev
        - python-setuptools
        - python-pip
        - iptables
        - ssh
    - name: openvswitch setup
      shell: ovs-vsctl set-manager ptcp:6640
      become: True
    - name: check out the repository on the host
      pip:
        name: ryu
    - name: ssh setup
      shell: >
        sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config;
        echo "root:ryu" | chpasswd;
    - name: restart service ssh
      service:
        name: ssh
        state: restarted
        become: True

- name: k8s deployment
  hosts: k8s
  tasks:
    - name: install apt packages
      apt: pkg=snapd update_cache=yes cache_valid_time=3600
      become: True
    - name: install microk8s
      snap:
        name: microk8s
        classic: yes
        channel: 1.13/stable
    - name: microk8s setup
      shell: install_microk8s.sh
      become: true

- name: devstack deployment
  hosts: devstack
  vars:
    repo_devstack: https://git.openstack.org/openstack-dev/devstack.git
    proj_path: "/home/vagrant/"
  tasks:
    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      become: True
      with_items:
        - git
        - crudini
    - name: download stack user creating script
      git: repo={{ repo_devstack }} dest={{ proj_path }} accept_hostke=yes
    - name: create stack user
      shell: create-stack-user.sh
      args:
        chdir: "{{ proj_path }}/devstack/tools/"
    - name: install devstack
      shell: install_devstack.sh
      become: true
    - name: Set the permissions for the RabbitMQ user
      rabbitmq_user:
        user: "stackrabbit"
        tags: "administrator"
        state: present
      become: True
    - name: copy
      copy:
        src: /home/vagrant/rabbitmq.config
        dest: /etc/rabbitmq/rabbitmq.config
      become: True
    - name: restart
      systemd:
        state: restarted
        daemon_reload: yes
        name: rabbitmq-server
      become: True