apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: evpn-mgmt-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evpn-api
  template:
    metadata:
      labels:
        app: evpn-api
    spec:
      containers:
      - name: evpn-api
        image: 28041980/rest_vtep_client
        ports:
        - name: http
          containerPort: 8080
