apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: evpn-agent-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evpn-agent
  template:
    metadata:
      labels:
        app: evpn-agent
    spec:
      containers:
      - name: evpn-agent
        image: 28041980/evpn-agent
        volumeMounts:
        - name: app-settings
          mountPath: /config
        ports:
        - name: bgp
          containerPort: 179
      volumes:
      - name: app-settings
        configMap:
          name: app-settings